In [93]:
# importing libraries
import pandas as pd
import numpy as np

In [94]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [95]:
# loading dataset
dataset = pd.read_csv('/content/drive/MyDrive/Kaggle_Dataset/world_export_import_dataset.csv')
dataset.head()

,Partner Name,Year,Export (US$ Thousand),Import (US$ Thousand),Export Product Share (%),Import Product Share (%),Revealed comparative advantage,World Growth (%),Country Growth (%),AHS Simple Average (%),...,MFN Total Tariff Lines,MFN Dutiable Tariff Lines Share (%),MFN Duty Free Tariff Lines Share (%),MFN Specific Tariff Lines Share (%),MFN AVE Tariff Lines Share (%),MFN MaxRate (%),MFN MinRate (%),MFN SpecificDuty Imports (US$ Thousand),MFN Dutiable Imports (US$ Thousand),MFN Duty Free Imports (US$ Thousand)
0,Aruba,1988,3498.10,328.49,100.0,100,NaN,NaN,NaN,2.80,...,1152.0,63.54,22.74,70.32,31.61,352.69,0.0,2186.00,3128.02,0.0
1,Afghanistan,1988,213030.40,54459.52,100.0,100,NaN,NaN,NaN,0.88,...,4142.0,69.41,15.64,72.45,40.51,2029.66,0.0,78436.91,94191.50,0.0
2,Angola,1988,375527.89,370702.76,100.0,100,NaN,NaN,NaN,2.02,...,5438.0,76.00,16.27,41.55,24.80,451.15,0.0,727741.99,921481.52,0.0
3,Anguila,1988,366.98,4.00,100.0,100,NaN,NaN,NaN,3.71,...,322.0,66.15,22.05,78.79,36.36,100.00,0.0,94.00,583.00,0.0
4,Albania,1988,30103.56,47709.30,100.0,100,NaN,NaN,NaN,1.84,...,5684.0,66.87,19.19,57.93,48.52,3000.00,0.0,37904.09,101195.95,0.0

In [96]:
# missing values in the dataset
missing_values = dataset.isnull().sum()
missing_values

Partner Name                                  0
Year                                          0
Export (US$ Thousand)                         0
Import (US$ Thousand)                         0
Export Product Share (%)                     20
Import Product Share (%)                      0
Revealed comparative advantage             3384
World Growth (%)                           3686
Country Growth (%)                         3686
AHS Simple Average (%)                       16
AHS Weighted Average (%)                     16
AHS Total Tariff Lines                       16
AHS Dutiable Tariff Lines Share (%)          16
AHS Duty Free Tariff Lines Share (%)         16
AHS Specific Tariff Lines Share (%)          16
AHS AVE Tariff Lines Share (%)               16
AHS MaxRate (%)                              16
AHS MinRate (%)                              16
AHS SpecificDuty Imports (US$ Thousand)      15
AHS Dutiable Imports (US$ Thousand)          15
AHS Duty Free Imports (US$ Thousand)         15
MFN Simple Average (%)                       15
MFN Weighted Average (%)                     15
MFN Total Tariff Lines                       15
MFN Dutiable Tariff Lines Share (%)          15
MFN Duty Free Tariff Lines Share (%)         15
MFN Specific Tariff Lines Share (%)          16
MFN AVE Tariff Lines Share (%)               16
MFN MaxRate (%)                              15
MFN MinRate (%)                              15
MFN SpecificDuty Imports (US$ Thousand)      15
MFN Dutiable Imports (US$ Thousand)          15
MFN Duty Free Imports (US$ Thousand)         15
dtype: int64

In [97]:
missing_values[missing_values > 0]

Export Product Share (%)                     20
Revealed comparative advantage             3384
World Growth (%)                           3686
Country Growth (%)                         3686
AHS Simple Average (%)                       16
AHS Weighted Average (%)                     16
AHS Total Tariff Lines                       16
AHS Dutiable Tariff Lines Share (%)          16
AHS Duty Free Tariff Lines Share (%)         16
AHS Specific Tariff Lines Share (%)          16
AHS AVE Tariff Lines Share (%)               16
AHS MaxRate (%)                              16
AHS MinRate (%)                              16
AHS SpecificDuty Imports (US$ Thousand)      15
AHS Dutiable Imports (US$ Thousand)          15
AHS Duty Free Imports (US$ Thousand)         15
MFN Simple Average (%)                       15
MFN Weighted Average (%)                     15
MFN Total Tariff Lines                       15
MFN Dutiable Tariff Lines Share (%)          15
MFN Duty Free Tariff Lines Share (%)         15
MFN Specific Tariff Lines Share (%)          16
MFN AVE Tariff Lines Share (%)               16
MFN MaxRate (%)                              15
MFN MinRate (%)                              15
MFN SpecificDuty Imports (US$ Thousand)      15
MFN Dutiable Imports (US$ Thousand)          15
MFN Duty Free Imports (US$ Thousand)         15
dtype: int64

In [98]:
dataset.shape

(8096, 33)

In [99]:
# total data in the dataset
total_dataset = np.product(dataset.shape)
total_dataset

267168

In [100]:
# total missing values
total_missing = missing_values.sum()
total_missing

11147

In [101]:
# total percentage of missing values
percent = (total_missing / total_dataset) * 100
percent

4.172281111510361

In [102]:
y = dataset['Export (US$ Thousand)']
y.head()

0      3498.10
1    213030.40
2    375527.89
3       366.98
4     30103.56
Name: Export (US$ Thousand), dtype: float64

In [103]:
drop = dataset.drop(['Export (US$ Thousand)'], axis = 1)
X = drop.select_dtypes(exclude = 'object')
X.head()

,Year,Import (US$ Thousand),Export Product Share (%),Import Product Share (%),Revealed comparative advantage,World Growth (%),Country Growth (%),AHS Simple Average (%),AHS Weighted Average (%),AHS Total Tariff Lines,...,MFN Total Tariff Lines,MFN Dutiable Tariff Lines Share (%),MFN Duty Free Tariff Lines Share (%),MFN Specific Tariff Lines Share (%),MFN AVE Tariff Lines Share (%),MFN MaxRate (%),MFN MinRate (%),MFN SpecificDuty Imports (US$ Thousand),MFN Dutiable Imports (US$ Thousand),MFN Duty Free Imports (US$ Thousand)
0,1988,328.49,100.0,100,NaN,NaN,NaN,2.80,2.92,155.0,...,1152.0,63.54,22.74,70.32,31.61,352.69,0.0,2186.00,3128.02,0.0
1,1988,54459.52,100.0,100,NaN,NaN,NaN,0.88,1.83,548.0,...,4142.0,69.41,15.64,72.45,40.51,2029.66,0.0,78436.91,94191.50,0.0
2,1988,370702.76,100.0,100,NaN,NaN,NaN,2.02,3.89,633.0,...,5438.0,76.00,16.27,41.55,24.80,451.15,0.0,727741.99,921481.52,0.0
3,1988,4.00,100.0,100,NaN,NaN,NaN,3.71,1.09,33.0,...,322.0,66.15,22.05,78.79,36.36,100.00,0.0,94.00,583.00,0.0
4,1988,47709.30,100.0,100,NaN,NaN,NaN,1.84,2.38,744.0,...,5684.0,66.87,19.19,57.93,48.52,3000.00,0.0,37904.09,101195.95,0.0

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size= 0.8, test_size= 0.2, random_state= 0)

In [105]:
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor

def score_data(X_train, X_test, y_train, y_test):
  model = RandomForestRegressor(n_estimators=100, random_state = 0)
  model.fit(X_train, y_train)
  pred = model.predict(X_test)
  return mean_absolute_error(y_test, pred)

**Approach 1 just remove missing columns**

In [106]:
missing_with_columns = [col for col in X_train.columns if X_train[col].isnull().sum()]

drop_X_train = X_train.drop(missing_with_columns, axis = 1)
drop_X_test = X_test.drop(missing_with_columns, axis = 1)

print(score_data(drop_X_train, drop_X_test, y_train, y_test))

25192768.309092674

**Approach 2 Imputation**

In [121]:
from sklearn.impute import SimpleImputer

impute = SimpleImputer()
imputed_X_train = pd.DataFrame(impute.fit_transform(X_train))
imputed_X_test = pd.DataFrame(impute.fit_transform(X_test))

imputed_X_train.columns = X_train.columns
imputed_X_test.columns = X_test.columns

print(score_data(imputed_X_train, imputed_X_test, y_train, y_test))

16089324.66169226

**Approach 3 improvising imputation** *italicized text*

In [124]:
X_train_plus = X_train.copy()
X_test_plus = X_test.copy()

for col in missing_with_columns:
  X_train_plus[col + "_was_missing"] = X_train_plus[col].isnull()
  X_test_plus[col + "_was_missing"] = X_test_plus[col].isnull()

imputed_X_train_plus = pd.DataFrame(impute.fit_transform(X_train_plus))
imputed_X_test_plus = pd.DataFrame(impute.fit_transform(X_test_plus))

imputed_X_train_plus.columns = X_train_plus.columns
imputed_X_test_plus.columns = X_test_plus.columns

print(score_data(imputed_X_train_plus, imputed_X_test_plus, y_train, y_test))

16251420.675775183